/* Real saved-game returns, guide steps and modeless inspectors on mobile. */
const fs=require('node:fs/promises'),path=require('node:path'),{execFileSync}=require('node:child_process')
const {chromium}=require('playwright'),{qaOrigin}=require('./lib/qa.cjs')
async function main(){
 const now=Date.now(),report={scans:[],actions:[],errors:[],missingArt:[]},out=path.resolve('docs/mockups')
 const source=await fs.readFile(path.join(__dirname,'layout-qa.cjs'),'utf8'),raw=source.slice(source.indexOf('function scanPage()'),source.indexOf('async function main()'))
 const scoped=raw.replace("document.querySelectorAll('.bp, .ika-top, .ika-nav, .quest-chip, .threat-banner, .island-view, .map-top-tools, .city-shortcuts, .city-activity, .title-screen, [role=\"dialog\"]')","document.querySelectorAll('.frg-card,.away-card,.building-inspector')");if(scoped===raw)throw Error('Scanner scope changed');const scan=new Function(`return (${scoped.trim()})`)()
 const seeds=JSON.parse(execFileSync('node',['--import','tsx','-e',`const fs=require('fs'),{initialEmpire,parseEmpire,advanceEmpire}=require('./lib/game/empire.ts'),{RESEARCH}=require('./lib/game/engine.ts'),{dispatchRaid,NPC_SETTLEMENTS}=require('./lib/game/expeditions.ts');const now=${now},base=parseEmpire(fs.readFileSync('tools/fixtures/late-game.json','utf8'));for(const c of base.cities){c.game.updatedAt=now;c.game.queue=[];c.game.drills=[];c.game.study=null;}base.missions=[];base.sieges=[];base.threats=[];base.nextThreat={};base.shipments=[];base.world.wars=[];base.world.start=now;const ready=advanceEmpire(base,now),quiet=structuredClone(ready);for(const c of quiet.cities)c.game.updatedAt=now-30*60000;const gains=structuredClone(quiet);for(const c of gains.cities){c.game.resources.gold=1000000;c.game.resources.wood=0;c.game.resources.knowledge=0;}gains.cities[0].game.drills=[{kind:'drill',id:'yeniceri',count:3,start:now-30*60000,end:now-29*60000}];const busy=structuredClone(base),start=now-30*86400000;for(const c of busy.cities)c.game.updatedAt=start;busy.world.start=start;const c=busy.cities[0];c.game.buildings.divan=8;c.game.queue=[{kind:'build',id:'divan',start,end:start+1000}];const rid=Object.keys(RESEARCH)[0];c.game.research=c.game.research.filter(r=>r!==rid);c.game.study={kind:'research',id:rid,start,end:start+1000};const sent=dispatchRaid(busy,NPC_SETTLEMENTS[0].id,{yeniceri:5},start);if(sent.error)throw Error(sent.error);console.log(JSON.stringify({guide:initialEmpire(now),quiet,gains,busy:sent.empire,inspector:ready}));`],{maxBuffer:4*1024*1024}).toString())
 const browser=await chromium.launch({headless:true,executablePath:process.env.QA_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']})
 try{for(const [width,height]of [[390,844],[360,740],[430,932]])for(const state of (process.env.SUPPORT_QA_STATES?.split(',')||['inspector','guide','quiet','gains','busy'])){
  const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1})
  await context.addInitScript(({now,seed,state})=>{Date.now=()=>now;localStorage.setItem('payitaht-qa','1');if(state!=='guide')localStorage.setItem('payitaht-rehber','goruldu');localStorage.setItem('payitaht-adalari-v1',JSON.stringify(seed))},{now,seed:seeds[state],state})
  const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(`${width}/${state}: ${e.message}`));page.on('response',r=>{if(r.status()>=400&&r.url().includes('/images/game/'))report.missingArt.push(r.url())})
  console.log('opening',width,state);await page.goto(qaOrigin('SUPPORT_QA_URL'),{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Devam et',exact:true}).click();await page.locator('.game-shell').waitFor();await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'})
  const restore=()=>page.evaluate(()=>document.querySelectorAll('[data-support-zoom]').forEach(el=>{el.style.fontSize=el.dataset.supportOriginalFont||'';delete el.dataset.supportZoom;delete el.dataset.supportOriginalFont}))
  const check=async label=>{console.log('scan',width,state,label);await restore();for(const zoom of [1,1.3]){if(zoom>1)await page.evaluate(z=>{const els=[...document.querySelectorAll('.frg-card,.frg-card *,.away-card,.away-card *,.building-inspector,.building-inspector *')].filter(el=>!(el instanceof SVGElement));const sizes=els.map(el=>parseFloat(getComputedStyle(el).fontSize));els.forEach((el,i)=>{el.dataset.supportOriginalFont=el.style.fontSize;el.style.fontSize=sizes[i]*z+'px';el.dataset.supportZoom='1'})},zoom);await page.waitForTimeout(100);const found=await page.evaluate(scan),total=Object.values(found).reduce((n,g)=>n+Object.values(g).reduce((s,x)=>s+x.adet,0),0);report.scans.push({width,state,label,zoom,total,found});if(total)console.log(JSON.stringify({width,state,label,zoom,found}));const card=page.locator('.frg-card,.away-card,.building-inspector').first();const skin=await card.evaluate(el=>({radius:getComputedStyle(el).borderRadius,frame:getComputedStyle(el).borderImageSource,rect:el.getBoundingClientRect().toJSON()}));if(skin.radius!=='0px'||!skin.frame.includes('unit-frame'))throw Error('Old window skin '+JSON.stringify(skin));if(skin.rect.top<0||skin.rect.bottom>height+1)throw Error('Window outside viewport');if(state==='guide'){const spot=await page.locator('.frg-spot').boundingBox();if(spot&&Math.min(spot.y+spot.height,skin.rect.bottom)-Math.max(spot.y,skin.rect.top)>1)throw Error('Guide covers its target');}}await restore();if(width===390){await page.screenshot({path:path.join(out,`support-${state}-${label}-390.webp`),type:'webp',quality:85})}}
  if(state==='guide'){
   for(let i=0;i<4;i++){await page.locator('.frg-card').waitFor();await check('step-'+(i+1));await page.locator('.frg-card').getByRole('button',{name:i===3?'Başlayalım':'İleri',exact:true}).click()}
   await page.locator('.frg').waitFor({state:'detached'});if(await page.evaluate(()=>localStorage.getItem('payitaht-rehber'))!=='goruldu')throw Error('Guide completion not saved');await page.reload();await page.getByRole('button',{name:'Devam et',exact:true}).click();await page.locator('.game-shell').waitFor();if(await page.locator('.frg').count())throw Error('Guide replayed');report.actions.push(`${width}: dört adım ve kalıcı tamamlama`)
  }else if(state==='inspector'){
   await page.waitForFunction(()=>!!window.__payitahtQa);for(const id of ['divan','medrese','kisla','ambar','liman']){await page.evaluate(id=>window.__payitahtQa.buildingPreview(id),id);await page.locator('.building-inspector').waitFor();await check(id);await page.keyboard.press('Escape');await page.locator('.building-inspector').waitFor({state:'detached'})}await page.evaluate(()=>window.__payitahtQa.buildingPreview('divan'));await page.getByRole('button',{name:'Yapıyı yönet',exact:false}).click();await page.locator('.bp').waitFor();if(await page.locator('.building-inspector').count())throw Error('Inspector remained over details');report.actions.push(`${width}: önizleme, Escape ve yönetim geçişi`)
  }else{
   await page.locator('.away-card').waitFor();if(state==='quiet')await page.locator('.away-quiet').waitFor();if(state==='gains'){await page.locator('.away-gains').waitFor();await page.getByText('Talimden çıkanlar',{exact:true}).waitFor()}if(state==='busy'){await page.getByText('Ustalar bitirdi',{exact:true}).waitFor();await page.getByText('Âlimler keşfetti',{exact:true}).waitFor();await page.locator('.away-full').first().waitFor();await page.getByRole('button',{name:'Raporlara bak',exact:true}).waitFor()}await check('return');if(state==='busy'){await page.getByRole('button',{name:'Raporlara bak',exact:true}).click();await page.locator('.bp-campaign').waitFor()}else await page.getByRole('button',{name:'Şehre dön',exact:true}).click();await page.locator('.away').waitFor({state:'detached'});report.actions.push(`${width}/${state}: gerçek çevrimdışı özet ve dönüş işlemi`)
  }
  await context.close();console.log(`checked ${width}/${state}`)
 }}finally{await browser.close()}
 report.clean=report.scans.every(s=>s.total===0)&&!report.errors.length&&!report.missingArt.length;await fs.writeFile(path.resolve('docs/support-qa-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({scans:report.scans.length,clean:report.clean,actions:report.actions.length,errors:report.errors,missingArt:report.missingArt}));if(!report.clean)process.exitCode=1
}
main().catch(e=>{console.error(e);process.exitCode=1})
