/* Mobile opening: inspect without changing a save, then test isolated starts. */
const fs=require('node:fs/promises'),path=require('node:path'),{execFileSync}=require('node:child_process')
const {chromium}=require('playwright'),{qaOrigin}=require('./lib/qa.cjs')
async function main(){
 const now=Date.now(),report={scans:[],actions:[],errors:[],missingArt:[]},out=path.resolve('docs/mockups');await fs.mkdir(out,{recursive:true})
 const source=await fs.readFile(path.join(__dirname,'layout-qa.cjs'),'utf8'),raw=source.slice(source.indexOf('function scanPage()'),source.indexOf('async function main()'))
 const scoped=raw.replace("document.querySelectorAll('.bp, .ika-top, .ika-nav, .quest-chip, .threat-banner, .island-view, .map-top-tools, .city-shortcuts, .city-activity, .title-screen, [role=\"dialog\"]')","document.querySelectorAll('.title-screen')");if(scoped===raw)throw Error('Scanner scope changed');const scan=new Function(`return (${scoped.trim()})`)()
 const empire=JSON.parse(execFileSync('node',['--import','tsx','-e',`const fs=require('fs'),{parseEmpire}=require('./lib/game/empire.ts');const e=parseEmpire(fs.readFileSync('tools/fixtures/late-game.json','utf8'));for(const c of e.cities){c.game.updatedAt=${now};c.game.queue=[];c.game.drills=[];c.game.study=null;}e.missions=[];e.sieges=[];e.threats=[];e.nextThreat={};e.shipments=[];e.world.wars=[];e.world.start=${now};e.cities[0].name='Uzun Adlı Ada Başkenti';e.profile={...e.profile,ruler:'Uzun Adlı Osmanlı Beyi',crest:'kartal',color:'#24406e',since:${now},motto:''};console.log(JSON.stringify(parseEmpire(JSON.stringify(e))));`],{cwd:path.resolve('.'),maxBuffer:4*1024*1024}).toString())
 const browser=await chromium.launch({headless:true,executablePath:process.env.QA_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']})
 try{for(const [width,height]of [[390,844],[360,740],[430,932]])for(const state of ['fresh','saved','corrupt','replace']){
  const saved=state==='fresh'?null:state==='corrupt'?'{bozuk-kayit':JSON.stringify(empire)
  const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1,timezoneId:'Europe/Istanbul'})
  await context.addInitScript(({now,saved})=>{Date.now=()=>now;localStorage.setItem('payitaht-qa','1');localStorage.setItem('payitaht-rehber','goruldu');if(saved===null)localStorage.removeItem('payitaht-adalari-v1');else localStorage.setItem('payitaht-adalari-v1',saved)},{now,saved})
  const page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>report.errors.push(`${width}/${state}: ${e.message}`));page.on('response',r=>{if(r.status()>=400&&r.url().includes('/images/game/'))report.missingArt.push(r.url())})
  await page.goto(qaOrigin('TITLE_QA_URL'),{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:state==='fresh'?'Hikâyeye başla':'Devam et',exact:true}).waitFor();await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'})
  const restore=()=>page.evaluate(()=>document.querySelectorAll('[data-qa-zoom]').forEach(el=>{el.style.fontSize=el.dataset.qaOriginalFont||'';delete el.dataset.qaZoom;delete el.dataset.qaOriginalFont}))
  const check=async label=>{await restore();if(label==='new'||label==='howto'||label==='notes'){const card=await page.locator('.title-card').evaluate(el=>({radius:getComputedStyle(el).borderRadius,frame:getComputedStyle(el).borderImageSource}));if(card.radius!=='0px'||!card.frame.includes('unit-frame'))throw Error(`Old card skin: ${JSON.stringify(card)}`);}for(const zoom of [1,1.3]){if(zoom>1)await page.evaluate(z=>{const els=[...document.querySelectorAll('.title-screen,.title-screen *')].filter(el=>!(el instanceof SVGElement));const sizes=els.map(el=>parseFloat(getComputedStyle(el).fontSize));els.forEach((el,i)=>{el.dataset.qaOriginalFont=el.style.fontSize;el.style.fontSize=`${sizes[i]*z}px`;el.dataset.qaZoom='1'})},zoom);await page.waitForTimeout(80);const found=await page.evaluate(scan),total=Object.values(found).reduce((n,g)=>n+Object.values(g).reduce((s,x)=>s+x.adet,0),0);report.scans.push({width,height,state,label,zoom,total,found});if(total)console.log(JSON.stringify({width,state,label,zoom,found}))}await restore();if(width===390&&((state==='fresh'&&['menu','howto','notes','new','error'].includes(label))||(state==='saved'&&['menu','confirm'].includes(label))||(state==='corrupt'&&label==='menu'))){if(label==='confirm')await page.locator('.title-screen').getByRole('alert').scrollIntoViewIfNeeded();else await page.locator('.title-screen').evaluate(el=>el.scrollTop=0);await page.screenshot({path:path.join(out,`title-${state}-${label}-390.webp`),type:'webp',quality:85})}}
  const unchanged=async()=>{const after=await page.evaluate(()=>localStorage.getItem('payitaht-adalari-v1'));if(after!==saved)throw Error(`Opening views changed ${state} save`)}
  await check('menu');if(state==='corrupt')await page.getByText('Kayıt korunuyor',{exact:false}).waitFor()
  if(state==='fresh'){
   await page.getByRole('button',{name:'Nasıl oynanır',exact:true}).click();await page.getByRole('heading',{name:'Nasıl oynanır?'}).waitFor();if(await page.locator('.title-howto li').count()!==6)throw Error('Missing how-to steps');await check('howto');await page.getByRole('button',{name:'Geri',exact:true}).click()
   await page.getByRole('button',{name:'Sürüm notları',exact:true}).click();await check('notes');const search=page.getByRole('searchbox',{name:'Sürüm arşivinde ara'});await search.fill('0.97.0');if(await page.locator('.annals-release').count()!==1)throw Error('Release search mismatch');await check('notes-search');await page.locator('.annals-release-toggle').click();await page.locator('.annals-release-toggle[aria-expanded=true]').waitFor();await check('notes-expanded');await page.getByRole('button',{name:'Hepsini kapat'}).click();await page.locator('.annals-release-toggle[aria-expanded=false]').waitFor();await check('notes-closed');await page.getByRole('button',{name:'Hepsini aç'}).click();await check('notes-open');await search.fill('bulunmayan-sürüm');await page.getByRole('heading',{name:'Arşivde eşleşme bulunamadı'}).waitFor();await check('notes-empty');await page.getByRole('button',{name:'Aramanı temizle'}).click();await check('notes-reset');await page.getByRole('button',{name:'Geri',exact:true}).click();report.actions.push(`${width}: yardım, sürüm arama ve açma/kapama çalıştı`)
  }
  await page.getByRole('button',{name:state==='fresh'?'Hikâyeye başla':'Yeni oyun',exact:true}).click();await page.locator('.title-form').waitFor();await check('new')
  for(const field of ['.title-crests','.title-colors']){const choices=page.locator(field+' button');if(await choices.count()!==12)throw Error('Expected twelve choices');for(let i=0;i<12;i++){await choices.nth(i).click();if(await page.locator(field+' button[aria-pressed=true]').count()!==1)throw Error('Selection must be unique')}}
  await page.locator('.title-crests').getByRole('button',{name:'Kitap',exact:true}).click();const colorButton=page.locator('.title-colors button').nth(2),color=await colorButton.evaluate(el=>el.style.background);await colorButton.click();await check('selected')
  await page.getByLabel('Hükümdarın adı',{exact:true}).fill(state==='fresh'?'A':'Ada Beyi');await page.getByLabel('Başkentin adı',{exact:true}).fill('Ay Limanı');await unchanged()
  if(state==='fresh'){await page.getByRole('button',{name:'Hikâyeye başla',exact:true}).click();await page.locator('.title-screen').getByRole('alert').waitFor();await check('error');await unchanged();await page.getByLabel('Hükümdarın adı',{exact:true}).fill('Ada Beyi')}
  else{await page.getByRole('button',{name:'Hikâyeye başla',exact:true}).click();await page.getByText('Bu cihazdaki eski şehrin silinecek.',{exact:false}).waitFor();await check('confirm');await unchanged();await page.getByRole('button',{name:'Vazgeç',exact:true}).click();await check('cancel');await unchanged();report.actions.push(`${width}/${state}: silme onayından vazgeçmek kaydı korudu`)}
  if(state==='fresh'||state==='replace'){
   if(state==='replace'){await page.getByRole('button',{name:'Yeni oyun',exact:true}).click();await page.getByRole('button',{name:'Hikâyeye başla',exact:true}).click();await page.getByRole('button',{name:'Evet, eskisini sil ve başla',exact:true}).click()}else await page.getByRole('button',{name:'Hikâyeye başla',exact:true}).click()
   await page.waitForFunction(()=>!!window.__payitahtQa&&!!document.querySelector('.game-shell'));const created=await page.evaluate(()=>JSON.parse(localStorage.getItem('payitaht-adalari-v1')));if(created.profile.ruler!=='Ada Beyi'||created.profile.crest!=='kitap'||created.cities[0].name!=='Ay Limanı')throw Error('New-game choices were not saved');const rgb=await page.evaluate(c=>{const el=document.createElement('span');el.style.background=c;return el.style.background},created.profile.color);if(rgb!==color)throw Error('Color not saved');report.actions.push(`${width}/${state}: ad, başkent, gerçek arma ve renk yeni kayda işlendi`)
  }else{
   await page.getByRole('button',{name:'Devam et',exact:true}).click();await page.locator('.game-shell').waitFor();if(state==='corrupt')await unchanged();else{const resumed=await page.evaluate(()=>JSON.parse(localStorage.getItem('payitaht-adalari-v1')));if(resumed.profile.ruler!==empire.profile.ruler||resumed.cities[0].name!==empire.cities[0].name)throw Error('Continue changed player identity')}report.actions.push(`${width}/${state}: devam et mevcut kaydı korudu`)
  }
  await context.close();console.log(`checked ${width}/${state}`)
 }}finally{await browser.close()}
 report.clean=report.scans.every(s=>s.total===0)&&!report.errors.length&&!report.missingArt.length;await fs.writeFile(path.resolve('docs/title-qa-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({scans:report.scans.length,clean:report.clean,actions:report.actions,errors:report.errors,missingArt:report.missingArt}));if(!report.clean)process.exitCode=1
}
main().catch(e=>{console.error(e);process.exitCode=1})
