/** G9: every research keeps its own painted motif and branch palette. */
import { RESEARCH, type ResearchBranch, type ResearchId } from '@/lib/game/engine'
import { AtlasArt, type ArtAtlas } from './deep-art'
import { Check } from './ui-art'

export const BRANCH: Record<ResearchBranch, [string, string]> = {
  ekonomi: ['#f1d9a0', '#b58a3a'],
  bilim: ['#cfe0ef', '#3d5f8a'],
  askeri: ['#f0c4b4', '#9a3324'],
  denizcilik: ['#cfe8ee', '#2f7a92'],
  mitoloji: ['#e3d3f0', '#6a4a8a'],
}
const ART: Record<ResearchId, { atlas: ArtAtlas; index: number }> = {
  tools: { atlas: 'research-ekonomi', index: 0 },
  storage: { atlas: 'research-ekonomi', index: 1 },
  ticaret: { atlas: 'research-ekonomi', index: 2 },
  makara: { atlas: 'research-ekonomi', index: 3 },
  geometri: { atlas: 'research-ekonomi', index: 4 },
  su_terazisi: { atlas: 'research-ekonomi', index: 5 },
  ormancilik: { atlas: 'research-ekonomi', index: 6 },
  tascilik: { atlas: 'research-ekonomi', index: 7 },
  kent_planlama: { atlas: 'research-ekonomi', index: 8 },
  ambar_teknigi: { atlas: 'research-ekonomi', index: 9 },
  bagcilik: { atlas: 'research-ekonomi', index: 10 },
  koruma: { atlas: 'research-ekonomi', index: 11 },
  zenginlik: { atlas: 'research-ekonomi', index: 12 },
  tatil: { atlas: 'research-ekonomi', index: 13 },
  mutfak: { atlas: 'research-ekonomi', index: 14 },
  yardim_eli: { atlas: 'research-ekonomi', index: 15 },
  yasama: { atlas: 'research-ekonomi', index: 16 },
  burokrasi: { atlas: 'research-ekonomi', index: 17 },
  utopya: { atlas: 'research-ekonomi', index: 18 },
  architecture: { atlas: 'research-bilim', index: 0 },
  alimler: { atlas: 'research-bilim', index: 1 },
  kagit: { atlas: 'research-bilim', index: 2 },
  murekkep: { atlas: 'research-bilim', index: 3 },
  mekanik_kalem: { atlas: 'research-bilim', index: 4 },
  simya: { atlas: 'research-bilim', index: 5 },
  camcilik: { atlas: 'research-bilim', index: 6 },
  optik: { atlas: 'research-bilim', index: 7 },
  tip: { atlas: 'research-bilim', index: 8 },
  kuyu: { atlas: 'research-bilim', index: 9 },
  casusluk: { atlas: 'research-bilim', index: 10 },
  devlet: { atlas: 'research-bilim', index: 11 },
  kultur: { atlas: 'research-bilim', index: 12 },
  anatomi: { atlas: 'research-bilim', index: 13 },
  deney: { atlas: 'research-bilim', index: 14 },
  din: { atlas: 'research-bilim', index: 15 },
  kus_ucusu: { atlas: 'research-bilim', index: 16 },
  matbaa: { atlas: 'research-bilim', index: 17 },
  kanat: { atlas: 'research-bilim', index: 18 },
  roket: { atlas: 'research-bilim', index: 19 },
  celik: { atlas: 'research-askeri', index: 0 },
  istihkam: { atlas: 'research-askeri', index: 1 },
  talim: { atlas: 'research-askeri', index: 2 },
  zirh: { atlas: 'research-askeri', index: 3 },
  barut: { atlas: 'research-askeri', index: 4 },
  askeri_lojistik: { atlas: 'research-askeri', index: 5 },
  muhendislik: { atlas: 'research-askeri', index: 6 },
  kusatma: { atlas: 'research-askeri', index: 7 },
  kuru_havuz: { atlas: 'research-askeri', index: 8 },
  meslek_ordusu: { atlas: 'research-askeri', index: 9 },
  seref: { atlas: 'research-askeri', index: 10 },
  balistik: { atlas: 'research-askeri', index: 11 },
  top_dokum: { atlas: 'research-askeri', index: 12 },
  pusula: { atlas: 'research-denizcilik', index: 0 },
  yelken: { atlas: 'research-denizcilik', index: 1 },
  haritacilik: { atlas: 'research-denizcilik', index: 2 },
  yukleme: { atlas: 'research-denizcilik', index: 3 },
  rum_atesi: { atlas: 'research-denizcilik', index: 4 },
  deniz_topculugu: { atlas: 'research-denizcilik', index: 5 },
  guverte: { atlas: 'research-denizcilik', index: 6 },
  korsanlik: { atlas: 'research-denizcilik', index: 7 },
  genisleme: { atlas: 'research-denizcilik', index: 8 },
  zift: { atlas: 'research-denizcilik', index: 9 },
  yabanci_kultur: { atlas: 'research-denizcilik', index: 10 },
  hafif_tekne: { atlas: 'research-denizcilik', index: 11 },
  ikmal: { atlas: 'research-denizcilik', index: 12 },
  havan: { atlas: 'research-denizcilik', index: 13 },
  zenberek: { atlas: 'research-denizcilik', index: 14 },
  dalgic: { atlas: 'research-denizcilik', index: 15 },
  buhar: { atlas: 'research-denizcilik', index: 16 },
  gemi_govdesi: { atlas: 'research-denizcilik', index: 17 },
  ongun_toresi: { atlas: 'research-mitoloji', index: 0 },
  balbal: { atlas: 'research-mitoloji', index: 1 },
  destan: { atlas: 'research-mitoloji', index: 2 },
  kam_ayini: { atlas: 'research-mitoloji', index: 3 },
  tore: { atlas: 'research-mitoloji', index: 4 },
  gok_kutu: { atlas: 'research-mitoloji', index: 5 },
}
export type EmblemState = 'done' | 'active' | 'open' | 'locked'
export function ResearchEmblem({ id, size = 56, state = 'open' }: { id: ResearchId; size?: number; state?: EmblemState }) {
  const a = ART[id]
  return <span className={`research-emblem is-${state}`} role="img" aria-label={RESEARCH[id].name}
    style={{ position: 'relative', display: 'inline-flex', width: size, height: size }}>
    <AtlasArt atlas={a.atlas} index={a.index} size={size} />
    {state === 'done' && <span style={{ position: 'absolute', right: 0, bottom: 0, width: 16, height: 16, borderRadius: '50%', background: '#2f6b4c', color: '#f6ecd6', display: 'grid', placeItems: 'center' }}><Check width={12} height={12} /></span>}
  </span>
}
